FESTIVAL_DB = {
    # ── Chaitra (0) ────────────────────────────────────────────────────────────
    (0, 0, 0):  "Ugadi / Telugu New Year",
    (0, 0, 2):  "Sree Rama Navami",        # Shukla Tritiya onwards (approximate — exact on Navami)
    (0, 0, 8):  "Sri Rama Navami",
    (0, 0, 11): "Kamada Ekadashi",
    (0, 0, 14): "Hanuman Jayanti",

    # ── Vaishakha (1) ──────────────────────────────────────────────────────────
    (1, 0, 2):  "Akshaya Tritiya",
    (1, 0, 10): "Mohini Ekadashi",
    (1, 0, 14): "Buddha Purnima",
    (1, 1, 10): "Apara Ekadashi",

    # ── Jyeshtha (2) ───────────────────────────────────────────────────────────
    (2, 0, 9):  "Ganga Dussehra",
    (2, 0, 10): "Nirjala Ekadashi",
    (2, 0, 14): "Vat Savitri Purnima",
    (2, 1, 10): "Yogini Ekadashi",
    (2, 1, 13): "Masik Shivaratri",

    # ── Ashadha (3) ────────────────────────────────────────────────────────────
    (3, 0, 1):  "Jagannath Rath Yatra",
    (3, 0, 10): "Toli Ekadashi (Devshayani)",
    (3, 0, 14): "Guru Purnima",
    (3, 1, 10): "Kamika Ekadashi",
    (3, 1, 13): "Masik Shivaratri",

    # ── Shravana (4) ───────────────────────────────────────────────────────────
    (4, 0, 4):  "Nagula Panchami",
    (4, 0, 10): "Putrada Ekadashi",
    (4, 0, 14): "Raksha Bandhan",
    (4, 1, 7):  "Sri Krishna Janmashtami",
    (4, 1, 10): "Aja Ekadashi",
    (4, 1, 13): "Masik Shivaratri",

    # ── Bhadrapada (5) ─────────────────────────────────────────────────────────
    (5, 0, 3):  "Vinayaka Chavithi",
    (5, 0, 10): "Parsva Ekadashi",
    (5, 0, 13): "Anant Chaturdashi",
    (5, 1, 7):  "Indira Ekadashi (Amaanta)",
    (5, 1, 10): "Indira Ekadashi",
    (5, 1, 13): "Masik Shivaratri",
    (5, 1, 14): "Mahalaya Amavasya",

    # ── Ashwina (6) ────────────────────────────────────────────────────────────
    (6, 0, 0):  "Devi Navaratri / Dasara Begins",
    (6, 0, 9):  "Vijaya Dashami / Dasara",
    (6, 0, 10): "Pashaankusha Ekadashi",
    (6, 0, 14): "Sharad Purnima / Kojagari",
    (6, 1, 2):  "Atla Tadde",
    (6, 1, 3):  "Karwa Chauth",
    (6, 1, 9):  "Rama Ekadashi",
    (6, 1, 12): "Dhanteras",
    (6, 1, 13): "Naraka Chaturdashi / Kali Chaudas",
    (6, 1, 14): "Deepavali / Diwali",

    # ── Kartika (7) ────────────────────────────────────────────────────────────
    (7, 0, 0):  "Govardhan Puja / Annakoot",
    (7, 0, 1):  "Bhai Dooj / Yama Dwitiya",
    (7, 0, 3):  "Nagula Chavithi",
    (7, 0, 10): "Utthana Dwadashi / Tulsi Vivah",
    (7, 0, 14): "Kartika Purnima / Karthika Deepam",
    (7, 1, 10): "Utpanna Ekadashi",
    (7, 1, 13): "Masik Shivaratri",

    # ── Margashirsha (8) ───────────────────────────────────────────────────────
    (8, 0, 10): "Mukkoti Ekadashi / Gita Jayanti / Vaikunta Ekadashi",
    (8, 0, 14): "Dattatreya Jayanti",
    (8, 1, 10): "Saphala Ekadashi",
    (8, 1, 13): "Masik Shivaratri",

    # ── Pausha (9) ─────────────────────────────────────────────────────────────
    (9, 0, 10): "Putrada Ekadashi (Pausha)",
    (9, 1, 10): "Shattila Ekadashi",
    (9, 1, 13): "Masik Shivaratri",

    # ── Magha (10) ─────────────────────────────────────────────────────────────
    (10, 0, 4):  "Vasant Panchami / Saraswati Puja",
    (10, 0, 6):  "Ratha Saptami",
    (10, 0, 7):  "Bhishmashtami",
    (10, 0, 10): "Bhishma Ekadashi / Jaya Ekadashi",
    (10, 0, 14): "Magha Purnima",
    (10, 1, 10): "Vijaya Ekadashi",
    (10, 1, 13): "Maha Shivaratri",

    # ── Phalguna (11) ──────────────────────────────────────────────────────────
    (11, 0, 10): "Amalaki Ekadashi",
    (11, 0, 14): "Holi / Holika Dahan",
    (11, 1, 10): "Papmochani Ekadashi",
    (11, 1, 13): "Masik Shivaratri",
}

GREGORIAN_FESTIVALS = {
    (1, 1):  "New Year's Day",
    (1, 13): "Bhogi",
    (1, 14): "Makara Sankranti / Pongal",
    (1, 15): "Kanuma / Mattu Pongal",
    (1, 16): "Mukkanuma",
    (1, 26): "Republic Day India",
    (2, 14): "Valentine's Day",
    (3, 8):  "Women's Day",
    (4, 14): "Ambedkar Jayanti / Vishu / Puthandu",
    (5, 1):  "Labor Day / May Day",
    (6, 21): "International Yoga Day",
    (8, 15): "Independence Day India",
    (10, 2): "Gandhi Jayanti",
    (11, 14):"Children's Day",
    (12, 25):"Christmas",
}

FESTIVAL_IMAGES_STATIC = {
    "Ugadi":           "/static/images/ugadi.jpg",
    "Rama Navami":     "/static/images/rama_navami.jpg",
    "Sree Rama":       "/static/images/rama_navami.jpg",
    "Hanuman":         "/static/images/hanuman.jpg",
    "Akshaya Tritiya": "/static/images/akshaya_tritiya.jpg",
    "Buddha":          "/static/images/guru_purnima.jpg",
    "Guru Purnima":    "/static/images/guru_purnima.jpg",
    "Rath Yatra":      "/static/images/janmashtami.jpg",
    "Raksha Bandhan":  "/static/images/raksha_bandhan.jpg",
    "Janmashtami":     "/static/images/janmashtami.jpg",
    "Krishna":         "/static/images/janmashtami.jpg",
    "Ganesh":          "/static/images/ganesh.jpg",
    "Vinayaka":        "/static/images/vinayaka.jpg",
    "Chavithi":        "/static/images/vinayaka.jpg",
    "Sankashti":       "/static/images/sankashti.jpg",
    "Sankashta":       "/static/images/sankashta.jpg",
    "Mahalaya":        "/static/images/durga.jpg",
    "Navratri":        "/static/images/navratri.jpg",
    "Navaratri":       "/static/images/navratri.jpg",
    "Dasara":          "/static/images/dussehra.jpg",
    "Dussehra":        "/static/images/dussehra.jpg",
    "Vijaya Dashami":  "/static/images/dussehra.jpg",
    "Durga":           "/static/images/durga.jpg",
    "Sharad Purnima":  "/static/images/guru_purnima.jpg",
    "Kojagari":        "/static/images/guru_purnima.jpg",
    "Atla Tadde":      "/static/images/ugadi.jpg",
    "Dhanteras":       "/static/images/deepavali.jpg",
    "Naraka":          "/static/images/deepavali.jpg",
    "Diwali":          "/static/images/diwali.jpg",
    "Deepavali":       "/static/images/deepavali.jpg",
    "Govardhan":       "/static/images/ugadi.jpg",
    "Bhai Dooj":       "/static/images/raksha_bandhan.jpg",
    "Nagula":          "/static/images/ugadi.jpg",
    "Tulsi Vivah":     "/static/images/ugadi.jpg",
    "Karthika":        "/static/images/deepavali.jpg",
    "Kartika Purnima": "/static/images/deepavali.jpg",
    "Vaikunta":        "/static/images/vishnu_ekadashi.png",
    "Gita Jayanti":    "/static/images/vishnu_ekadashi.png",
    "Mukkoti":         "/static/images/vishnu_ekadashi.png",
    "Dattatreya":      "/static/images/guru_purnima.jpg",
    "Vasant Panchami": "/static/images/ugadi.jpg",
    "Saraswati":       "/static/images/ugadi.jpg",
    "Ratha Saptami":   "/static/images/ugadi.jpg",
    "Shivaratri":      "/static/images/shivaratri.jpg",
    "Maha Shiva":      "/static/images/shivaratri.jpg",
    "Holi":            "/static/images/holi.jpg",
    "Holika":          "/static/images/holi.jpg",
    "Ekadashi":        "/static/images/vishnu_ekadashi.png",
    "Pradosh":         "/static/images/pradosh.jpg",
    "Pradosham":       "/static/images/pradosh.jpg",
    "Sankranti":       "/static/images/makara_sankranti.png",
    "Pongal":          "/static/images/makara_sankranti.png",
    "Bhogi":           "/static/images/makara_sankranti.png",
    "Kanuma":          "/static/images/makara_sankranti.png",
    "Mukkanuma":       "/static/images/makara_sankranti.png",
    "Christmas":       "/static/images/christmas.jpg",
    "Republic":        "/static/images/republic.jpg",
    "Independence":    "/static/images/independence.jpg",
    "Yoga":            "/static/images/yoga.jpg",
    "Ganga":           "/static/images/guru_purnima.jpg",
    "Rath":            "/static/images/janmashtami.jpg",
    "Purnima":         "/static/images/guru_purnima.jpg",
    "Amavasya":        "/static/images/shivaratri.jpg",
}
