FESTIVAL_DB = {
    (0, 0, 0): "Ugadi / Gudi Padwa", 
    (0, 0, 8): "Sri Rama Navami", 
    (0, 0, 14): "Hanuman Jayanti", 
    (1, 0, 2): "Akshaya Tritiya", 
    (1, 0, 14): "Buddha Purnima", 
    (2, 0, 9): "Ganga Dussehra", 
    (2, 0, 14): "Vat Savitri Vrat", 
    (3, 0, 1): "Jagannath Rath Yatra", 
    (3, 0, 10): "Toli Ekadashi (Devshayani)", 
    (3, 0, 14): "Guru Purnima", 
    (4, 0, 4): "Nagula Panchami", 
    (4, 0, 14): "Raksha Bandhan", 
    (4, 1, 7): "Sri Krishna Janmashtami", 
    (5, 0, 3): "Vinayaka Chavithi", 
    (5, 0, 13): "Anant Chaturdashi", 
    (5, 1, 14): "Mahalaya Amavasya", 
    (6, 0, 0): "Devi Navaratri Start", 
    (6, 0, 9): "Vijaya Dashami", 
    (6, 0, 14): "Sharad Purnima", 
    (6, 1, 2): "Atla Tadde",
    (6, 1, 3): "Karwa Chauth", 
    (6, 1, 12): "Dhanteras", 
    (6, 1, 13): "Naraka Chaturdashi",
    (6, 1, 14): "Deepavali", 
    (7, 0, 0): "Govardhan Puja", 
    (7, 0, 1): "Bhai Dooj", 
    (7, 0, 3): "Nagula Chavithi (Start)",
    (7, 0, 10): "Utthana Dwadashi / Tulsi Vivah", 
    (7, 0, 14): "Kartika Purnima", 
    (8, 0, 10): "Mukkoti Ekadashi / Gita Jayanti", 
    (8, 0, 14): "Dattatreya Jayanti", 
    (10, 0, 4): "Vasant Panchami", 
    (10, 0, 6): "Ratha Saptami", 
    (10, 0, 10): "Bhishma Ekadashi",
    (10, 1, 13): "Maha Shivaratri", 
    (11, 0, 14): "Holi / Kamadahan"
}

GREGORIAN_FESTIVALS = {
    (1, 1): "New Year's Day", 
    (1, 13): "Bhogi",
    (1, 14): "Makara Sankranti / Pongal", 
    (1, 15): "Kanuma",
    (1, 26): "Republic Day India", 
    (2, 14): "Valentine's Day", 
    (3, 8): "Women's Day", 
    (4, 14): "Ambedkar Jayanti", 
    (5, 1): "Labor Day", 
    (6, 21): "International Yoga Day", 
    (8, 15): "Independence Day India", 
    (10, 2): "Gandhi Jayanti", 
    (11, 14): "Children's Day", 
    (12, 25): "Christmas"
}

FESTIVAL_IMAGES_STATIC = {
    "Ugadi": "/static/images/ugadi.jpg", 
    "Rama Navami": "/static/images/rama_navami.jpg", 
    "Hanuman": "/static/images/hanuman.jpg", 
    "Akshaya Tritiya": "/static/images/akshaya_tritiya.jpg", 
    "Guru Purnima": "/static/images/guru_purnima.jpg", 
    "Raksha Bandhan": "/static/images/raksha_bandhan.jpg", 
    "Janmashtami": "/static/images/janmashtami.jpg", 
    "Ganesh": "/static/images/ganesh.jpg", 
    "Vinayaka": "/static/images/vinayaka.jpg", 
    "Sankashti": "/static/images/sankashti.jpg", 
    "Sankashta": "/static/images/sankashta.jpg",
    "Navratri": "/static/images/navratri.jpg", 
    "Durga": "/static/images/durga.jpg", 
    "Dussehra": "/static/images/dussehra.jpg", 
    "Vijaya": "/static/images/vijaya.jpg",
    "Diwali": "/static/images/diwali.jpg", 
    "Deepavali": "/static/images/deepavali.jpg",
    "Shivaratri": "/static/images/shivaratri.jpg", 
    "Holi": "/static/images/holi.jpg", 
    "Ekadashi": "/static/images/vishnu_ekadashi.png", 
    "Pradosh": "/static/images/pradosh.jpg", 
    "Sankranti": "/static/images/makara_sankranti.png", 
    "Pongal": "/static/images/makara_sankranti.png",
    "Christmas": "/static/images/christmas.jpg", 
    "Republic": "/static/images/republic.jpg", 
    "Independence": "/static/images/independence.jpg", 
    "Yoga": "/static/images/yoga.jpg"
}
